# official tutorial
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/

site_name: "Ed Shelton's Knowledge Base"
theme:
  name: material
  #  favicon: attachment/portrait.png
  language: en
  features:
    - navigation.instant
    # - navigation.indexes
    # - toc.integrate
    - tabs
    - content.tabs.link
    - navigation.tabs
    # - navigation.sections
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
        # icon: material/toggle-switch
        icon: material/weather-night
        name: Switch to Dark Mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        # icon: material/toggle-switch-off-outline
        icon: material/weather-sunny
        name: Switch to Light Mode
  font:
    text: Intra
    code: JetBrains Mono
markdown_extensions:
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: '#'
      slugify: !!python/name:pymdownx.slugs.uslugify
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
plugins:
  - search
  - roamlinks
  - exclude:
      glob:
        - "*.tmp"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
  - glightbox
  - awesome-pages
  - git-revision-date-localized:
      timezone: America/Chicago
      exclude:
          - index.md
      # type: iso_date
      # enable_creation_date: true
  - redirects:
      redirect_maps:
          'old.md': 'databases/concepts/Databases.md'
extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:ed@edshelton.org
    - icon: fontawesome/brands/github
      link: https://github.com/edsheltonorg
copyright: Copyright &copy; 2023 Ed Shelton
