# official tutorial
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/

site_name: "Ed Shelton Knowledge Base"
theme:
  name: material
  #  favicon: attachment/portrait.png
  language: en
  features:
    - navigation.expand
    - tabs
    - content.tabs.link
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
        # icon: material/toggle-switch
        icon: material/weather-night
        name: Switch to Dark Mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        # icon: material/toggle-switch-off-outline
        icon: material/weather-sunny
        name: Switch to Light Mode
  font:
    # text: Comic Neue
    text: Inter
    code: JetBrains Mono
markdown_extensions:
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - nl2br # newline-to-break
  - toc:
      permalink: '#' # heading anchor
      slugify: !!python/name:pymdownx.slugs.uslugify
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
plugins:
  - search
  - roamlinks
  # - offline
    #- autolinks
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
  - glightbox
extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:ed@edshelton.org
    - icon: fontawesome/brands/github
      link: https://github.com/edsheltonorg

copyright: Copyright &copy; 2023 Ed Shelton
