site_name: "Ed Shelton"
site_description: "Home for sane and simple answers."
site_author: "Ed Shelton"
copyright: Copyright &copy; 2023 Ed Shelton

repo_url: https://github.com/edsheltonorg/edshelton.org
repo_name: edshelton.org

theme:
  name: material
  language: en
  logo: assets/cat.png
  favicon: assets/favicon/favicon.ico
  icon:
    repo: octicons/code-24
    edit: material/pencil-box
    view: material/code-not-equal-variant

  font:
    text: Intra
    code: JetBrains Mono

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tabs.link
    # - header.autohide
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    # - navigation.indexes
    # - navigation.sections
    - tabs
    # - toc.integrate

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
      linenums: false
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: '#'
      slugify: !!python/name:pymdownx.slugs.uslugify

plugins:
  - awesome-pages
  - exclude:
      glob:
        - "*.tmp"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
  - git-revision-date-localized:
      timezone: America/Chicago
      exclude:
          - index.md
  - glightbox
  - redirects:
      redirect_maps:
          'old.md': 'databases/concepts/Databases.md'
  - roamlinks
  - search

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:ed@edshelton.org
    - icon: fontawesome/brands/github
      link: https://github.com/edsheltonorg
